### ISSUE TITLE
Add functionality to the exit button in the picture taking flow

### ISSUE THREAD

**Issue by eduardb** [theaiscope/GDD-app#12]
Clicking the top-left exit button on any of the three screens of the picture taking flow (Capture, Mask/Highlight and Metadata) should display a confirmation modal dialog as in [this Invision screen](https://invis.io/RNT0MSVUEJ6#/375927255_4-3_Metadata_-_Exit). The positive option will exit the flow to the homepage.

**Comment by davidegavio** [comment]
I'd like to work on it!

**Comment by eduardb** [comment]
Hi, @davidegavio! Thanks for showing your interest. Let us know if you have any questions. Looking forward to your contribution!

**Comment by eduardb** [comment]
Done in #13
