### ISSUE TITLE
Add lint and fix issues

### ISSUE THREAD

**Issue by eduardb** [theaiscope/GDD-app#16]
What the title says.

**Comment by VivekSingh777** [comment]
Can I grab this issue?

**Comment by eduardb** [comment]
Hi @VivekSingh777! Yes, please, go for it :)

**Comment by eduardb** [comment]
Hi @VivekSingh777! Do you have any updates on this? Take also into consideration breaking it down in several iterations, doing everything in one go might be too much of an effort.

**Comment by VivekSingh777** [comment]
Sorry I don't required resources to install this on my local. Can u reassign to some one else.

**Comment by eduardb** [comment]
Sure, no problem. Thanks for showing your interest in the first place :)

**Comment by subbramanil** [comment]
@eduardb Let me take a stab at it. 

Bit confused about 'Add lint'.

From Android Studio, I see the below results. 

[Lint Results](https://www.dropbox.com/s/yrr507odsh71vm9/Screen%20Shot%202019-10-16%20at%2012.20.11%20AM.png?dl=0)

I can't promise that I can fix everything, but I'm confident about most of it. 

Let me know

**Comment by eduardb** [comment]
Hi @subbramanil! Sorry for getting back this late to you.
Yes, you are right, Lint is already running, that was a mistake from my part. Maybe what else could be done would be making the build fail if new lint errors are added.
Feel free to fix as much as you can, and then just create a baseline for the rest. We like to iterate :) 
Cheers!
