### ISSUE TITLE
Downscale images larger than the maximum bitmap size

### ISSUE THREAD

**Issue by eduardb** [theaiscope/GDD-app#21]
In the mask layer, we are loading a large bitmap that comes from the camera. However, on some devices, this bitmap exceeds the maximum size that can be loaded in a canvas. For example, on a Redmi 6A device, the picture is 3120x4160 in size, whereas the maximum bitmap can be 4096x4096. 
As a solution, downscale the image so that it fits in the constraints.

See https://stackoverflow.com/questions/7428996/hw-accelerated-activity-how-to-get-opengl-texture-size-limit

**Comment by jbors** [comment]
Yo @eduardb I _think_ this should be fixed now. Any QA you wanna do before closing the issue?

**Comment by eduardb** [comment]
#55, #59 and #63 should close this issue, no need to do more QA apart from what we did already.
